### ISSUE TITLE
/MINT encode failure

### ISSUE THREAD

**Issue by hududed** [bikemonkeytech/cNFT_TESTNET_bot#2]
From the Daedalus logs I see I am using `cardano-cli` 1.26.2, running on macOS 11.4.

I gave this code a test run, all ran well until /MINT process, got this error:

```
cardano-cli: encodeFailure: local state query: using acquire without a Point must be conditional on negotiating v8 of the node-to-client protocol
CallStack (from HasCallStack):
  error, called at src/Ouroboros/Network/Protocol/LocalStateQuery/Codec.hs:79:7 in ouroboros-network-0.1.0.0-25ehGe7xai35S1L2oSV2hq:Ouroboros.Network.Protocol.LocalStateQuery.Codec
```
In telegram it's stuck here: 
```
Checking for transaction confirmation.

OK, I found the Transaction, thank you.

Please be patient as I build your NFT and send it back to you with your change in ADA.

Starting NFT Minting process......
```
Please advise.

**Comment by hududed** [comment]
Additional info from the `logging.log`:

```
2021-06-06 15:22:51,835 - root - INFO - Session Data Created: 17d88aa3-7c5a-42e3-819f-37a34b20815e - STP
2021-06-06 15:22:51,835 - root - INFO - Bot Address: addr_test1qpwy20xa84x6rltqlt8fe4sqa9cf2f3m7xht3z38ur07e9s8jcc23vfm2am5r7faxtru2nmpmzsyz4ah7yszag70wzyqr06s9j
2021-06-06 15:24:51,801 - root - INFO - ******* CHAT INFO ********
2021-06-06 15:24:51,802 - root - INFO - {'username': 'hudwahab', 'user_id': 1530544113, 'message_id': 77, 'is_bot': False}
2021-06-06 15:24:51,802 - root - INFO - ***************
2021-06-06 15:24:51,805 - root - INFO - Looking for UTXOs in bot address: 17d88aa3-7c5a-42e3-819f-37a34b20815e - STP
2021-06-06 15:24:52,260 - root - INFO - ['2754f66f833631a47e40c211b05d4ef87602a0330bc97bf1af12077b0d71864a', '0', '5000000', 'lovelace']
2021-06-06 15:24:53,375 - root - INFO - Minting started for 17d88aa3-7c5a-42e3-819f-37a34b20815e
2021-06-06 15:24:53,379 - root - INFO - Session Found: 17d88aa3-7c5a-42e3-819f-37a34b20815e
2021-06-06 15:24:53,406 - root - INFO -
2021-06-06 15:24:53,407 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "/Users/hud/cNFT_TESTNET_bot/app.py", line 273, in put_mint
    minted = mint(**sesh)
  File "/Users/hud/cNFT_TESTNET_bot/token_utils.py", line 270, in mint
    current_slot = get_current_slot()
  File "/Users/hud/cNFT_TESTNET_bot/token_utils.py", line 48, in get_current_slot
    data = json.loads(response)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

**Comment by bikemonkeytech** [comment]
The cardano-cli was updated and they removed the era arguments.  They also changed the protocol-parameters and the way that the tip query returns.

I updated the code so that it now works and bumped the code version to 0.0.8 in the config.py

**Comment by hududed** [comment]
the previous error is solved but getting this error:
```
2021-06-08 11:03:31,307 - root - INFO - Session Found: c6b63bec-0e95-427c-a7ef-a879405ce52d
2021-06-08 11:03:31,375 - root - INFO - {
    "hash": "668a1663dfeb588db7fee1f91bfd9dafa5983c31fe0e35e0a3b358feac1933b7",
    "block": 2654707,
    "slot": 28802567,
    "epoch": 136
}

2021-06-08 11:03:31,376 - root - INFO - Current Slot:  28802567
2021-06-08 11:03:31,430 - root - INFO - ['e5c071c994c1ad25aee0163512c4ae30d77a300d30420df354d5e6e5c37abf7b', '0', '5000000', 'lovelace']
2021-06-08 11:03:31,874 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 447, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "/Users/hud/cNFT_TESTNET_bot/app.py", line 273, in put_mint
    minted = mint(**sesh)
  File "/Users/hud/cNFT_TESTNET_bot/token_utils.py", line 292, in mint
    tx_details = get_tx_details(utxo[0])
  File "/Users/hud/cNFT_TESTNET_bot/token_utils.py", line 55, in get_tx_details
    res.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cardano-testnet.blockfrost.io/api/v0/txs/e5c071c994c1ad25aee0163512c4ae30d77a300d30420df354d5e6e5c37abf7b/utxos
```
I might have something wrong written in for `BLOCKFROST_TESTNET` - is this the same as `BLOCKFROST_API` ?
